onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/rst_i
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/clk_i
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/BPADDR_i
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/CLKCNT_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/IFpc_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/IFinstruction_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/IDpc_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/IDinstruction_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/EXpc_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/EXinstruction_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/MEMpc_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/MEMinstruction_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/WBpc_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/WBinstruction_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/STRIGGER_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/FHCNT_o
add wave -noupdate -group TB -radix hexadecimal /tb_rv32i/STCNT_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/rst_i
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/clk_i
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/BPADDR_i
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/CLKCNT_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/IFpc_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/IFinstruction_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/IDpc_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/IDinstruction_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/EXpc_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/EXinstruction_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/MEMpc_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/MEMinstruction_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/WBpc_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/WBinstruction_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/STRIGGER_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/FHCNT_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/STCNT_o
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/mclk_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/mclk_cnt_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/PCwrite_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/Strigger_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/IFIDwrite_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/if_pc_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/if_pcplus4_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/if_instr_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ifid_pc_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ifid_pcplus4_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ifid_instr_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_regdst_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_alusrc_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_memtoreg_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_regwrite_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_memread_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_memwrite_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_branch_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_jal_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_jalr_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_wbsrc_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_mul_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_upperim_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_aluop_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_mulop_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_rdata1_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_rdata2_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/id_signext_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_pc_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_pcplus4_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_instr_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_rdata1_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_rdata2_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_signext_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_rs1_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_rs2_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_rd_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_aluop_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_upperim_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_mulop_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_alusrc_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_wbsrc_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_regwrite_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_memread_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_memwrite_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_memtoreg_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_regdst_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_branch_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_jal_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_jalr_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/idex_mul_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/forwardA_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/forwardB_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ex_brtaken_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ex_alures_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ex_addrgen_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ex_P0_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ex_P1_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ex_P2_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ex_P3_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/ex_rs2_fwd_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_pc_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_pcplus4_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_instr_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_alures_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_rdata2_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_addrgen_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_P0_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_P1_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_P2_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_P3_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_mulop_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_rd_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_regwrite_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_memread_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_memwrite_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_memtoreg_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_regdst_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_wbsrc_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_branch_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_jal_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_jalr_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_brtaken_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/exmem_mul_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/mem_mulres_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/mem_dtcm_rd_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/mem_dtcm_addr_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/redirect_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/redirect_pc_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/mem_mux_res_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_pc_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_pcplus4_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_instr_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_mux_res_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_mul2_res_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_dtcm_rd_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_rd_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_regwrite_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_wbsrc_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_memtoreg_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/memwb_regdst_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/wb_mux_res_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/wbid_mux_res_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/stall_w
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/clkcnt_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/stcnt_q
add wave -noupdate -group CORE -radix hexadecimal /tb_rv32i/CORE/fhcnt_q
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/ifid_instuction_i
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/idex_rd_i
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/idex_regwrite_i
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/idex_memread_i
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/idex_mul_i
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/stall_o
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/PCwrite_o
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/IFIDwrite_o
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/opc_w
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/rs1_w
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/rs2_w
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/use_rs1_w
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/use_rs2_w
add wave -noupdate -group HazardUnit -radix hexadecimal /tb_rv32i/CORE/Hzrd/noForward_w
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/clk_i
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/rst_i
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/PCwrite_i
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/redirect_i
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/redirect_pc_i
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/BPADDR_i
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/pc_o
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/pc_plus4_o
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/instruction_o
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/STRIGGER_o
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/pc_q
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/pc_plus4_q
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/pc_plus4_r
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/itcm_addr_w
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/next_pc_w
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/rst_q
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/STRIGGER_w
add wave -noupdate -group Fetch -radix hexadecimal /tb_rv32i/CORE/IFE/BPADDR_q
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/clk_i
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/rst_i
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/pc_plus4_i
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/instruction_i
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/write_data_i
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/RegWrite_ctrl_i
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/wb_rd_i
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/read_data1_o
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/read_data2_o
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/SignExt_o
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/RF_q
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/opc_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/rs1_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/rs2_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/rd_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/Iimm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/Simm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/SBimm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/Uimm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/UJimm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/SignExt_Iimm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/SignExt_Simm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/SignExt_SBimm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/SignExt_Uimm_w
add wave -noupdate -group Decode -radix hexadecimal /tb_rv32i/CORE/ID/SignExt_UJimm_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/instruction_i
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/RegDst_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/ALUSrc_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/MemtoReg_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/RegWrite_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/MemRead_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/MemWrite_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/Branch_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/Jal_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/Jalr_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/WBSrc_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/mul_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/UpperIm_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/ALUOp_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/MULOp_ctrl_o
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/Rtype_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/Itype_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/Stype_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/SBtype_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/Utype_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/UJtype_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/lb_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/lh_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/lw_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/lbu_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/lhu_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/lwu_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/ld_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/sb_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/sh_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/sw_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/st_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/beq_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/bne_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/blt_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/bge_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/bltu_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/bgeu_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/branch_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/jal_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/jalr_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/add_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/addi_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/and_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/andi_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/or_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/ori_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/sll_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/slli_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/sra_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/srai_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/srl_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/srli_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/sub_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/xor_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/xori_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/auipc_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/lui_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/slt_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/slti_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/sltu_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/sltiu_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/mul_w
add wave -noupdate -group Control -radix hexadecimal /tb_rv32i/CORE/CTL/opc_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/read_data1_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/read_data2_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/sign_extend_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/UpperIm_ctrl_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/ALUOp_ctrl_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/MULOp_ctrl_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/ALUSrc_ctrl_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/pc_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/WBSrc_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/mem_res_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/wb_res_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/ForwardA_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/ForwardB_i
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brTaken_o
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/alu_res_o
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/addr_gen_o
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/P0_o
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/P1_o
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/P2_o
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/P3_o
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/rs2_fwd_o
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/ain_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/ain_mux_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/bin_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/bin_mux_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/sub_res_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/ltu_res_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/eq_res_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/msbneq_res_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/alu_res_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brTaken_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shl_s1_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shl_s2_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shl_s3_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shl_s4_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shr_s1_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shr_s2_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shr_s3_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shr_s4_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/brl_shr_pad_r
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/al_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/ah_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/bl_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/bh_w
add wave -noupdate -group Execute -radix hexadecimal /tb_rv32i/CORE/EXE/forwarded_rs2_w
add wave -noupdate -group Mul2 -radix hexadecimal /tb_rv32i/CORE/MUL/P0_i
add wave -noupdate -group Mul2 -radix hexadecimal /tb_rv32i/CORE/MUL/P1_i
add wave -noupdate -group Mul2 -radix hexadecimal /tb_rv32i/CORE/MUL/P2_i
add wave -noupdate -group Mul2 -radix hexadecimal /tb_rv32i/CORE/MUL/P3_i
add wave -noupdate -group Mul2 -radix hexadecimal /tb_rv32i/CORE/MUL/MULOp_ctrl_i
add wave -noupdate -group Mul2 -radix hexadecimal /tb_rv32i/CORE/MUL/Mul_res_o
add wave -noupdate -group Mul2 -radix hexadecimal /tb_rv32i/CORE/MUL/M_w
add wave -noupdate -group Mul2 -radix hexadecimal /tb_rv32i/CORE/MUL/MULTI_res_r
add wave -noupdate -group ForwardingUnit -radix hexadecimal /tb_rv32i/CORE/FU/idex_rs1_i
add wave -noupdate -group ForwardingUnit -radix hexadecimal /tb_rv32i/CORE/FU/idex_rs2_i
add wave -noupdate -group ForwardingUnit -radix hexadecimal /tb_rv32i/CORE/FU/exmem_rd_i
add wave -noupdate -group ForwardingUnit -radix hexadecimal /tb_rv32i/CORE/FU/exmem_regwrite_i
add wave -noupdate -group ForwardingUnit -radix hexadecimal /tb_rv32i/CORE/FU/memwb_rd_i
add wave -noupdate -group ForwardingUnit -radix hexadecimal /tb_rv32i/CORE/FU/memwb_regwrite_i
add wave -noupdate -group ForwardingUnit -radix hexadecimal /tb_rv32i/CORE/FU/forwardA_o
add wave -noupdate -group ForwardingUnit -radix hexadecimal /tb_rv32i/CORE/FU/forwardB_o
add wave -noupdate -group Memory -radix hexadecimal /tb_rv32i/CORE/MEM/clk_i
add wave -noupdate -group Memory -radix hexadecimal /tb_rv32i/CORE/MEM/rst_i
add wave -noupdate -group Memory -radix hexadecimal /tb_rv32i/CORE/MEM/dtcm_addr_i
add wave -noupdate -group Memory -radix hexadecimal /tb_rv32i/CORE/MEM/dtcm_data_wr_i
add wave -noupdate -group Memory -radix hexadecimal /tb_rv32i/CORE/MEM/MemRead_ctrl_i
add wave -noupdate -group Memory -radix hexadecimal /tb_rv32i/CORE/MEM/MemWrite_ctrl_i
add wave -noupdate -group Memory -radix hexadecimal /tb_rv32i/CORE/MEM/dtcm_data_rd_o
add wave -noupdate -group Memory -radix hexadecimal /tb_rv32i/CORE/MEM/wrclk_w
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {396982203 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 423
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {396982203 ps} {398706655 ps}
